/** @type {import('tailwindcss').Config} */
const withAlpha = (variable) => `rgb(var(${variable}) / <alpha-value>)`

export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        kupan: {
          black: withAlpha('--color-bg-primary'),
          charcoal: withAlpha('--color-bg-secondary'),
          iron: withAlpha('--color-bg-card'),
          gray: withAlpha('--color-bg-elevated'),
          bone: withAlpha('--color-text-primary'),
          muted: withAlpha('--color-text-muted'),
          ember: withAlpha('--color-brand-red'),
          flame: withAlpha('--color-brand-sand'),
          red: withAlpha('--color-error'),
          success: withAlpha('--color-success'),
          warning: withAlpha('--color-warning'),
          info: withAlpha('--color-info'),
          border: withAlpha('--color-border-default'),
          root: withAlpha('--color-brand-red'),
          'root-hover': withAlpha('--color-brand-red-hover'),
          forest: withAlpha('--color-brand-forest'),
          leaf: withAlpha('--color-brand-leaf'),
          earth: withAlpha('--color-brand-earth'),
          sand: withAlpha('--color-brand-sand'),
          steel: withAlpha('--color-brand-steel'),
        },
        'bg-primary': withAlpha('--color-bg-primary'),
        'bg-secondary': withAlpha('--color-bg-secondary'),
        'bg-card': withAlpha('--color-bg-card'),
        'bg-elevated': withAlpha('--color-bg-elevated'),
        'text-primary': withAlpha('--color-text-primary'),
        'text-secondary': withAlpha('--color-text-secondary'),
        'text-muted': withAlpha('--color-text-muted'),
        'border-default': withAlpha('--color-border-default'),
        'border-strong': withAlpha('--color-border-strong'),
        'brand-red': withAlpha('--color-brand-red'),
        success: withAlpha('--color-success'),
        warning: withAlpha('--color-warning'),
      },
      spacing: {
        1: '0.25rem',
        2: '0.5rem',
        3: '0.75rem',
        4: '1rem',
        6: '1.5rem',
        8: '2rem',
        10: '2.5rem',
        12: '3rem',
      },
      borderRadius: {
        md: '0.5rem',
        lg: '0.75rem',
        xl: '0.5rem',
        '2xl': '0.5rem',
      },
      boxShadow: {
        glow: '0 0 24px rgb(var(--color-brand-red) / 0.22)',
      },
      fontFamily: {
        display: ['"Barlow Condensed"', 'Inter', 'system-ui', 'sans-serif'],
        ceremonial: ['"Cormorant Garamond"', 'Georgia', 'serif'],
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
